---
- name: install httpd
  package:
    name=httpd
    state=latest
- name: ensure apache is running
  service: name=httpd state=started enabled=yes
- name: capture output of id command
  command: id -un
  register: login
- copy:
    dest: "/var/www/html/index.html"  
    content: Hello World! from {{ login.stdout }}@{{ansible_default_ipv4.address}}
